version: "3.8"
services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./bitrix.cnf:/etc/mysql/conf.d/bitrix.cnf
  debian_bitrix:
    image: serega170584/bitrix_site
    volumes:
      - ./httpd_server.conf:/etc/apache2/sites-available/httpd_server.conf
      - ./httpd_server_link.conf:/etc/apache2/sites-enabled/httpd_server_link.conf
      - ./ports.conf:/etc/apache2/ports.conf
      - ./nginx_server.conf:/etc/nginx/sites-available/nginx_server.conf
      - ./nginx_server_link.conf:/etc/nginx/sites-enabled/nginx_server_link.conf
      - ./local:/var/www/html/bitrix/local
      - ./project:/var/www/html/bitrix/project
    build: .
    ports:
      - "80:80"