version: "3.8"
services:
  debian_bitrix:
    build: .
    command: service nginx start
    volumes:
    - test_vol:/test_vol
    ports:
    - "80:80"
    stdin_open: true
    tty: true
volumes:
  test_vol: